login:
  # ç¬¬ä¸€æ¬¡ä½¿ç”¨è¯·ç™»å½•
  enable: NO


search:
  enable: NO
  interval: 300
  keywords:
    - æ–©æ€çº¿
    - æ®–
    - å…¬çŸ¥
    - NGO
    - åŠ³a


comment:
  interval: 15
  min_pubdate:
    year:   2026
    month:  1
    day:    12
    hour:   18
    minute: 0
    second: 0
  max_time_since_pub:
    day:    1
    hour:   0

  templates:
    - :wins;:stickers;
    - :stickers;:wins;

  vars:
    stickers:
      - :sticker;
      - :sticker;:sticker;

    sticker:
      - '[æ˜Ÿæ˜Ÿçœ¼]'
      - '[æ‰“call]'
      - '[æ»‘ç¨½]'
      - '[å¦™å•Š]'
      - '[å—‘ç“œå­]'
      - '[å‘²ç‰™]'
      - '[å¤§ç¬‘]'
      - '[å·ç¬‘]'
      - '[é¼“æŒ]'
      - '[å˜˜å£°]'
      - '[æ‚çœ¼]'
      - '[æƒŠå–œ]'
      - '[å“ˆæ¬ ]'
      - '[æŠ“ç‹‚]'

    wins:
      - :win;
      - :won;

    win:
      - 'èµ¢'
      - 'ğŸ¥‡èµ¢'
      - 'èµ¢ğŸ¥‡'
      - 'âœŒèµ¢'

    won:
      - 'èµ¢äº†'
      - 'âœŒèµ¢äº†'
      - 'èµ¢äº†âœŒ'
      - 'ğŸ¥‡èµ¢äº†'
