login:
  # ç¬¬ä¸€æ¬¡ä½¿ç”¨è¯·ç™»å½•
  # æ— æ³•é‡è½½
  enable: NO


search:
  # æ— æ³•é‡è½½
  enable: YES

  interval: 20

  keywords:
    - æ–©æ€çº¿
    - æ®–
    - å…¬çŸ¥
    - åŠ³a
    - åè´¼
    - æ„æ—
    - è¯»è€…
    - å·æ™®
    - ç¾å›½ ice
    - æ—©è‹—
    - é«˜å
    - ç™½ç¾½äºº
    - åŒ—å·´æ‹‰ç‰¹
    - 365èµ¢

    - è¯»é’æ„æ‚å¿—å®˜æ–¹
    - èƒ¡å¾‹å¸ˆ
    - å¤§å¤´é¹°
    - ç™½å°è¹
    - èµ›é›·
    - å£«å£åŠ I


comment:
  interval: 40

  cooldown:
    hour:   3
    minute: 0
    second: 0

  min_pubdate:
    year:   2000
    month:  1
    day:    1
    hour:   0
    minute: 0
    second: 0

  auto_clear_after_time:
    day:    3
    hour:   0

  templates:
    - :wins;:stickers;
    - :stickers;:wins;

  vars:
    stickers:
      - :sticker;
      - :sticker;:sticker;

    sticker:
      - '[æ˜Ÿæ˜Ÿçœ¼]'
      - '[æ‰“call]'
      - '[æ»‘ç¨½]'
      - '[å¦™å•Š]'
      - '[å—‘ç“œå­]'
      - '[å‘²ç‰™]'
      - '[å¤§ç¬‘]'
      - '[å·ç¬‘]'
      - '[é¼“æŒ]'
      - '[å˜˜å£°]'
      - '[æ‚çœ¼]'
      - '[æƒŠå–œ]'
      - '[å“ˆæ¬ ]'
      - '[æŠ“ç‹‚]'

    wins:
      - :win;
      - :won;

    win:
      - 'èµ¢'
      - 'ğŸ¥‡èµ¢'
      - 'èµ¢ğŸ¥‡'
      - 'âœŒèµ¢'

    won:
      - 'èµ¢äº†'
      - 'âœŒèµ¢äº†'
      - 'èµ¢äº†âœŒ'
      - 'ğŸ¥‡èµ¢äº†'
