search:
  # æ— æ³•é‡è½½
  # could NOT be reloaded
  enable: YES

  interval: 20

  keywords:
    - æ–©æ€çº¿
    - æ®–
    - å…¬çŸ¥
    - åŠ³a
    - åè´¼
    - æ„æ—
    - è¯»è€…
    - å·æ™®
    - ç¾å›½ ice
    - æ—©è‹—
    - é«˜å
    - ç™½ç¾½äºº
    - åŒ—å·´æ‹‰ç‰¹
    - 365èµ¢
    - çµè§†

    - è¯»é’æ„æ‚å¿—å®˜æ–¹
    - èƒ¡å¾‹å¸ˆ
    - å¤§å¤´é¹°
    - ç™½å°è¹
    - èµ›é›·
    - å£«å£åŠ I
    - æ³¢å£«é¡¿åœ†è„¸


comment:
  interval: 120

  cooldown:
    hour:   2
    minute: 0
    second: 0

  min-pubdate:
    year:   2000
    month:  1
    day:    1
    hour:   0
    minute: 0
    second: 0

  auto-clear-delay:
    day:    10
    hour:   0

  templates:
    - :wins;:stickers;
    - :stickers;:wins;

  vars:
    stickers:
      - :sticker;
      - :sticker;:sticker;

    sticker:
      - '[æ˜Ÿæ˜Ÿçœ¼]'
      - '[æ‰“call]'
      - '[æ»‘ç¨½]'
      - '[å¦™å•Š]'
      - '[å—‘ç“œå­]'
      - '[å‘²ç‰™]'
      - '[å¤§ç¬‘]'
      - '[å·ç¬‘]'
      - '[é¼“æŒ]'
      - '[å˜˜å£°]'
      - '[æ‚çœ¼]'
      - '[æƒŠå–œ]'
      - '[å“ˆæ¬ ]'
      - '[æŠ“ç‹‚]'

    wins:
      - :win;
      - :won;

    win:
      - 'èµ¢'
      - 'ğŸ¥‡èµ¢'
      - 'èµ¢ğŸ¥‡'
      - 'âœŒï¸èµ¢'

    won:
      - 'èµ¢äº†'
      - 'âœŒï¸èµ¢äº†'
      - 'èµ¢äº†âœŒï¸'
      - 'ğŸ¥‡èµ¢äº†'


url:
  placeholder: '{}'
  homepage:    'https://www.bilibili.com/'
  video-api:   'https://api.bilibili.com/x/web-interface/view?bvid={}'
  video:       'https://www.bilibili.com/video/{}/'
  search:      'https://search.bilibili.com/all?keyword={}&from_source=webtop_search&search_source=5&order=pubdate'


toast-keyword:
  cd-ban:        'cd'
  not-logged-in: 'æœªç™»å½•'
